//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Question()
        {
            this.Tbl_Answer = new HashSet<Tbl_Answer>();
        }
    
        public System.Guid PK_QuestionId { get; set; }
        public string QuestionType { get; set; }
        public string QuestionCategory { get; set; }
        public int QuestionLevel { get; set; }
        public string QuestionTitle { get; set; }
        public string QuestionText { get; set; }
        public bool QuestionIsActive { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public string QuestionImageUrl1 { get; set; }
        public string QuestionImageUrl2 { get; set; }
        public string QuestionFileUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Answer> Tbl_Answer { get; set; }
    }
}
