//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Payment
    {
        public System.Guid PK_PaymentId { get; set; }
        public System.Guid FK_UserId { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool IsVerified { get; set; }
        public string TransactionId { get; set; }
        public string CallbackMeetDatetime { get; set; }
        public string SendError { get; set; }
        public string RecieveError { get; set; }
        public string HashTransaction { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
