//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_User()
        {
            this.Tbl_Answer = new HashSet<Tbl_Answer>();
            this.Tbl_Payment = new HashSet<Tbl_Payment>();
            this.Tbl_Ticket = new HashSet<Tbl_Ticket>();
        }
    
        public System.Guid PK_UserId { get; set; }
        public string Mobile { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string SignupCode { get; set; }
        public System.DateTime SignupCodeExpireTime { get; set; }
        public string ResetPassCode { get; set; }
        public System.DateTime ResetCodeExpireTime { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int WritingAvailable { get; set; }
        public int SpeakingAvailable { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Answer> Tbl_Answer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Payment> Tbl_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Ticket> Tbl_Ticket { get; set; }
    }
}
